package com.EventIq.EventIq.Entities.enums;

public enum Genre {
    CONCERTS,
    THEATRE,
    COMEDY_SHOWS,
    SPORTS_EVENTS,
    CRICKET,
    FOOTBALL,
    BASKETBALL,
    WORKSHOPS,
    FESTIVALS,
    FOOD_DRINK_EVENTS,
    CONFERENCES,
    EXHIBITIONS,
    FAMILY_ACTIVITIES,
    NETWORKING_EVENTS,
    PARTIES_NIGHTLIFE,
    ADVENTURE_ACTIVITIES,
    CULTURAL_EVENTS,
    FITNESS_CLASSES
}
